name: DiscordAccountLinked
main: dev.guilhermeds.Main
version: 1.0
api-version: 1.21
description: This plugin links a Minecraft account with a Discord account, intended only as a proof of concept and not for production use.
commands:
  link:
    description: Links your Minecraft account with your Discord account.
    usage: /link <code>